### ISSUE TITLE
I can no longer properly instantiate my models.

### ISSUE THREAD

**Issue by isaackearl** [romanbican/repository#1]
You removed modelName and modelFolder as options for the repositories.

I need a way to load the location of my models.  

if I don't set $model it says it can't find my model in /Aviago/Repositories/<modelName>... which is folder where my repositories are.

If I do set "model" then it will just use it as a string rather then get the actual class.

also the setModel() no longer accepts a parameter so I can't set it manually.

I could create my own extension repository and add this functionality myself, so let me know if you want me to do that.  I could also make a pull request with changes if you really want me to, but it seems you already had it setup previously...

**Comment by romanbican** [comment]
Oh sorry. I didn't thing anyone is actually using this package. I use it in one project and I changed it because of it. If it doesn't work for you, please require oldest tag in your composer.json file. If you want, make PR. I'm sorry again.

**Comment by romanbican** [comment]
1.1.1 is probably tag you want.
